### ISSUE TITLE
Prereqs Require C Compiler for Installation

### ISSUE THREAD

**Issue by zoffixznet** [maxmind/MaxMind-DB-Reader-perl#15]
`Math::Int128` is in the chain of dependencies and it not only requires a C compiler, but one with 128-bit int support.

I think that defeats the whole point of having a Pure Perl version of this module, since had I access to a compiler, I could use the ::XS version anyway.

I couldn't install `Math::Int128` even on my non-restricted Debian test server (even though the docs say my compiler should work). On a production box, I don't even have access to a C compiler.

Is there any way to make this Pure Perl module work with... well, pure Perl?

```
Checking for int __attribute__ ((__mode__ (TI)))... no

  It looks like your compiler doesn't support a 128-bit integer type (one of
  "int __attribute__ ((__mode__ (TI)))" or "__int128"). One of these types is
  necessary to compile the Math::Int128 module.

N/A
! Configure failed for Math-Int128-0.22. See /home/zoffix/.cpanm/work/1428519131.24132/build.log for details.
! Installing the dependencies failed: Module 'Math::Int128' is not installed
! Bailing out the installation for MaxMind-DB-Common-0.031003.
```

**Comment by oschwald** [comment]
Thanks for the feedback, and you are right that this really should be changed to work with pure Perl. The primary issue blocking this is that the database format includes a 128-bit unsigned integer type that is difficult to support without this module. However, I think we could likely use `bigint` in place of it. PRs are welcome. :-)
