### ISSUE TITLE
Scalar::Util 1.38 test failures

### ISSUE THREAD

**Issue by Grinnz** [maxmind/MaxMind-DB-Reader-perl#16]
Scalar::Util 1.38 and 1.39 (1.38 is built-in with perl 5.20.2) leads to test failures such as in this report: http://www.cpantesters.org/cpan/report/388ba3a2-c644-11e4-b221-9e126cbd7f71

I had the same test failures installing MaxMind::DB::Reader and upgrading to Scalar::Util 1.40 or above fixed the issue.

**Comment by oschwald** [comment]
This should be fixed in v1.000006. Thanks for the report.
