### ISSUE TITLE
PP.pm not recognising IPv6 addresses?

### ISSUE THREAD

**Issue by jw35** [maxmind/MaxMind-DB-Reader-perl#24]
I'm puzzled by line 76 of lib/MAxMind/DB/Reader/PP/pm:

    my $is_ipv6_addr  = $addr =~ /::/;

This seems to cause IPv6 addresses not containing :: to be treated as IPv4 addresses, with obvious consequences. There are lots of valid IPv6 addresses that don't contain '::', surely that should be ':'?

Installing the XS version of the reader has worked around the problem for me, but recorded here in case it's useful.

Jon.

**Comment by oschwald** [comment]
Yes, you are right. This is obviously a bug.
