### ISSUE TITLE
Are there any packages available ?

### ISSUE THREAD

**Issue by waghanza** [maxmind/MaxMind-DB-Reader-perl#32]
Hello,

I use [MaxMind](https://www.maxmind.com) `geo-localization` database for business purpose.

I need to use the **mdb** database (instead of _legacy_ **dat** databases).

Are the available system packages available (`deb` or else)

Regards,

**Comment by oschwald** [comment]
We currently do not provide Debian packages for our Perl APIs.

**Comment by waghanza** [comment]
And for `geoipupdate` ?

**Comment by oschwald** [comment]
We have a [PPA for Ubuntu](https://launchpad.net/~maxmind/+archive/ubuntu/ppa). `geoipupdate` is also in Debian, Ubuntu, Fedora, etc.

**Comment by waghanza** [comment]
Ok. I have made my own `rpm` for `fedora` => https://packagecloud.io/waghanza/maxmind

**Comment by waghanza** [comment]
Will it be useful to use a tool for allowing **devs** to use `MaxMind` apps, such as :
+ http://appimage.org
+ https://snapcraft.io
+ http://flatpak.org/

**Comment by oschwald** [comment]
We are no longer making enhancements to our Perl APIs. As such, I am closing this.
