### ISSUE TITLE
Thread safety of MaxMind::DB::Reader::PP

### ISSUE THREAD

**Issue by andrii-suse** [maxmind/MaxMind-DB-Reader-perl#37]
It looks that object of `MaxMind::DB::Reader->new` is thread safe only if it uses `MaxMind::DB::Reader::XS` .
May I ask to clarify in documentation whether implementation of MaxMind::DB::Reader::PP is thread safe?

**Comment by oschwald** [comment]
As you say, it is likely not thread safe. We aren't actively updating this module, but I'll leave this open as a consideration if another release is done. A PR would also be welcomed.

**Comment by andrii-suse** [comment]
Thank you for your prompt reply. I posted the question based on personal experience, so proper PR would need quite an additional effort. So it is fine with me if it just stays open until somebody has specific confirmation.

**Comment by oschwald** [comment]
I am going to close this. It is unlikely we will do another release of this distribution unless a security issue is found.
